### ISSUE TITLE
double ? in url

### ISSUE THREAD

**Issue by theskillwithin** [delicious-simplicity/next-image-contentful-loader#2]
```
import Image from 'next/future/image'
....
                  <Image
                    loader={(props) =>
                      contentfulLoader(props, {
                        w: 1000,
                        h: 400,
                        fit: 'fill',
                        fm: 'webp',
                        q: 75,
                      })
                    }
                    src={photo.url}
                    quality={40}
                    width={photo.width}
                    height={photo.height}
                    alt={photo.title}
                    aria-label={photo.description}
                    priority
                    style={{ objectFit: 'cover', width: '100%', height: '100%' }}
                  />
```
somehow url comes out to this.  
`.jpg?fm=webp?w=3840&fit=fill&fm=webp&q=40`

**Comment by devjmetivier** [comment]
@theskillwithin It looks like your issue has to do with whatever URL gets passed to your image component.

In the example you gave `.jpg?fm=webp?w=3840&fit=fill&fm=webp&q=40` I see `fm=webp` twice far apart from each other in the string. This tells me that the variable URL getting passed probably has query parameters already attached to it.

I would suggest stripping off any query parameters before supplying it to the image component. Closing for now.
